# Generated by Django 4.0 on 2022-01-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrama_gantt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
    ]
