# Generated by Django 4.0 on 2022-01-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrama_gantt', '0002_remove_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
