@startuml
'https://plantuml.com/class-diagram

class Proyecto{
    - nombre_proyecto: String
    + agregar_colaborador(usuario:Usuario)
}

class Usuario{
    - username: String
    - password : String
    - grupo : Group
}

class ProyectoUsuario{
    + {static} tiene_proyectos(usuario:Usuario):boolean
    + {static} obtener_proyectos(usuario:Usuario): Proyecto[]
    + {static} crear_proyecto(nombre_proyecto:String, usuario_creador:Usuario):Proyecto
}

Proyecto "*" -- "*" Usuario
Proyecto .. ProyectoUsuario
@enduml